name = "rss-to-telegram"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[triggers]
crons = ["0 * * * *"]  # Run once every hour

[[kv_namespaces]]
binding = "RSS_STORAGE"
id = "18e000c9064e46188c116a42adfb34d3"